server:
  port: 9700

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

project:
  title: 文件服务中心
  swagger:
    enable: true

minio:
  endpoint: http://192.168.26.24:9000  #服务器链接
  accessKey: minioadmin
  secretKey: minioadmin
  domain: http://192.168.26.24:9000  #对外访问的域名  比如 http://www.xxx.com