server:
  port: 9401

project:
  title: WEB
  swagger:
    enable: true
  server-url:
    user-server-domain: http://localhost:9300
    game-server-domain: http://localhost:9500
  telegram:
    register-password: 123456

spring:
#  security:
#    user:
#      name: baisha
#      password: baisha
  redis:
    host: localhost
    timeout: 10000
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 32
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 32
        # 连接池中的最小空闲连接 默认 0
        min-idle: 2